name: Publish to npm
author: pascalgn
description: Automatically publish new versions to npm

inputs:
  commit_pattern:
    description: The pattern that matches version update commits.
    required: false
  tag_name:
    description: The name of the tag that you want to create for the version.
    required: false
  tag_message:
    description: The message of the tag that you want to create for the version.
    required: false
  workspace:
    description: Custom workspace directory that contains the package.json file.
    required: false

outputs:
  tag_name:
      description: "The tag name used for the new version"
  is_tagged_release:
      description: "Boolean if a tagged version has been used"
  has_published:
      description: "Boolean if NPM package has been published successfully"

runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: blue
